apiVersion: k8s.f5net.com/v3
kind: F5SPKEgress
metadata:
  name: awsbnkctl-egress
  namespace: {{.EgressNamespace}}
spec:
  snatType: SRC_TRANS_AUTOMAP
  pseudoCNIConfig:
    namespaces:
    - {{.Namespace}}
    appPodInterface: eth0
    vxlan:
      create: true
      tmmInterfaceName: {{.TmmIntVlan}}
{{- if .NodeIfname}}
      nodeInterfaceName: {{.NodeIfname}}
{{- end}}
      ipv4Subnet: "192.168.0.0"
      ipv4PrefixLen: 16
      ipv6Subnet: "fd50::"
      ipv6PrefixLen: 112

