// Package state manages the IDs cache file (.awsbnkctl/<cluster>/state.env).
//
// The file format is shell-source-compatible KEY=VALUE lines so operators can
// source it for manual inspection, matching the vars.env pattern from
// aws-gpu-setup. The Go interface is a typed map with Load/Save/Get/Set.
//
// Rules:
//   - Missing file → returns an empty State (not an error). This is the
//     expected state on first run.
//   - Corrupt file (non KEY=VALUE line) → returns an error.
//   - Save writes atomically (temp file + rename) to avoid partial writes.
//   - The file is listed in .gitignore and must never be committed.
//
// See docs/POST_TERRAFORM_DIRECTION.md §10 for the full format spec.
package state

import (
	"bufio"
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"time"
)

// State holds the IDs cache for a single cluster. Keys are upper-case
// shell variable names (e.g. "VPC_ID", "IGW_ID"). Values are the
// corresponding AWS resource IDs or ARNs.
//
// Later slices add keys by calling Set — no code change required because
// the backing store is a plain map.
type State struct {
	dir  string
	data map[string]string
}

// Load reads the state.env file from dir. If the file does not exist, Load
// returns an empty State — this is normal on first run and allows up to
// proceed to phase 00 without error. If the file exists but contains a
// malformed line, Load returns a non-nil error.
func Load(dir string) (*State, error) {
	s := &State{dir: dir, data: make(map[string]string)}

	path := s.path()
	f, err := os.Open(path)
	if os.IsNotExist(err) {
		return s, nil
	}
	if err != nil {
		return nil, fmt.Errorf("opening state %s: %w", path, err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	lineNum := 0
	for scanner.Scan() {
		lineNum++
		line := strings.TrimSpace(scanner.Text())
		if line == "" || strings.HasPrefix(line, "#") {
			continue
		}
		idx := strings.IndexByte(line, '=')
		if idx < 1 {
			return nil, fmt.Errorf("state %s line %d: expected KEY=VALUE, got %q", path, lineNum, line)
		}
		key := line[:idx]
		val := line[idx+1:]
		s.data[key] = val
	}
	if err := scanner.Err(); err != nil {
		return nil, fmt.Errorf("reading state %s: %w", path, err)
	}
	return s, nil
}

// Get returns the value for key, or "" if not present.
func (s *State) Get(key string) string {
	return s.data[key]
}

// Set stores key=value in memory. Call Save to persist.
func (s *State) Set(key, value string) {
	s.data[key] = value
}

// Save writes the in-memory state to state.env atomically. The directory is
// created if it does not exist. The file is written to a temp name and
// renamed so a partial write never corrupts the existing file.
func (s *State) Save() error {
	if err := os.MkdirAll(s.dir, 0o755); err != nil {
		return fmt.Errorf("mkdir %s: %w", s.dir, err)
	}

	tmp := s.path() + ".tmp"
	f, err := os.Create(tmp)
	if err != nil {
		return fmt.Errorf("creating temp state: %w", err)
	}

	fmt.Fprintf(f, "# Generated by awsbnkctl on %s — do not edit by hand\n",
		time.Now().UTC().Format(time.RFC3339))
	for k, v := range s.data {
		fmt.Fprintf(f, "%s=%s\n", k, v)
	}

	if err := f.Close(); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("closing temp state: %w", err)
	}
	if err := os.Rename(tmp, s.path()); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("renaming state file: %w", err)
	}
	return nil
}

// path returns the full path to the state.env file.
func (s *State) path() string {
	return filepath.Join(s.dir, "state.env")
}

// Dir returns the directory this State writes to (for tests / inspection).
func (s *State) Dir() string { return s.dir }
