package tf

import (
	"fmt"
	"io"
	"os"
	"strings"

	"github.com/JLCode-tech/awsbnkctl/internal/config"
)

// WriteTFVars renders the workspace config into terraform.tfvars at path.
// AWS credentials are NOT written — the SDK + terraform aws provider
// resolve them from the standard chain at apply time (env, profile,
// instance role, SSO).
//
// kubeconfigDir / scratchDir are rendered when non-empty. Both require
// the upstream TF to declare matching root-level variables.
func WriteTFVars(path string, ws *config.Workspace, kubeconfigDir, scratchDir string) error {
	f, err := os.Create(path)
	if err != nil {
		return fmt.Errorf("creating %s: %w", path, err)
	}
	defer f.Close()
	return RenderTFVars(f, ws, kubeconfigDir, scratchDir)
}

// RenderTFVars writes the tfvars body to w. Exposed for tests / callers
// that want to inspect the rendering before committing it to disk.
//
// Only fields the user has explicitly set in config.yaml are emitted —
// the rest fall through to the upstream TF module's own defaults.
//
// Sprint 2 (PRD 04 fold) retargets the renderer onto the AWS-shaped
// `aws:` block (Workspace.AWS); the legacy IBMCloud block still loads
// from disk (workspace.go alias) but no IBM-shaped tfvars are emitted.
//
// IMPORTANT: no credentials are written.  AWS credentials resolve via
// the SDK default chain; the IBM Cloud API key path (the cred package)
// stays out of tfvars by design.
func RenderTFVars(w io.Writer, ws *config.Workspace, kubeconfigDir, scratchDir string) error {
	if _, err := fmt.Fprintln(w, "# Generated by awsbnkctl. Do not edit by hand — run `awsbnkctl init` to update."); err != nil {
		return err
	}
	if _, err := fmt.Fprintln(w, "# AWS credentials are NOT written here; the SDK chain resolves them at apply time."); err != nil {
		return err
	}
	fmt.Fprintln(w)

	// AWS — PRD 04 fold (Sprint 2). Back-compat: fall back to the
	// inherited IBMCloud.Region if the AWS block is unset on a
	// legacy workspace.
	region := ws.AWS.Region
	if region == "" {
		region = ws.IBMCloud.Region
	}
	if region != "" {
		fmt.Fprintf(w, "region = %q\n", region)
	}
	if ws.AWS.VPCID != "" {
		fmt.Fprintf(w, "vpc_id = %q\n", ws.AWS.VPCID)
	}
	if len(ws.AWS.SubnetIDs) > 0 {
		fmt.Fprintf(w, "subnet_ids = %s\n", renderStringList(ws.AWS.SubnetIDs))
	}
	if ws.Cluster.Name != "" {
		fmt.Fprintf(w, "cluster_name = %q\n", ws.Cluster.Name)
	}

	// Supply-chain inputs (PRD 08). Only emit if the operator
	// supplied them at init time — defaults in the s3_supply_chain
	// module cover the rest.
	if p := ws.AWS.SupplyChain.FARArchivePath; p != "" {
		fmt.Fprintf(w, "far_auth_file_local_path = %q\n", p)
	}
	if p := ws.AWS.SupplyChain.JWTPath; p != "" {
		fmt.Fprintf(w, "jwt_file_local_path = %q\n", p)
	}
	if k := ws.AWS.SupplyChain.KMSKeyARN; k != "" {
		fmt.Fprintf(w, "kms_key_arn = %q\n", k)
	}
	if ws.AWS.SupplyChain.EnableECRMirror {
		fmt.Fprintln(w, "enable_ecr_mirror = true")
	}
	if ns := ws.AWS.SupplyChain.FLONamespace; ns != "" {
		fmt.Fprintf(w, "flo_namespace = %q\n", ns)
	}

	// Kubeconfig + scratch dirs. Pre-existing wiring; the upstream
	// TF tolerates undeclared values with a warning.
	if kubeconfigDir != "" {
		fmt.Fprintf(w, "kubeconfig_dir = %q\n", kubeconfigDir)
	}
	if scratchDir != "" {
		fmt.Fprintf(w, "scratch_dir = %q\n", scratchDir)
	}

	return nil
}

// renderStringList formats a Go []string as an HCL string list:
//
//	["a", "b", "c"]
//
// Keeps the renderer self-contained without pulling in an HCL writer.
func renderStringList(in []string) string {
	parts := make([]string, len(in))
	for i, s := range in {
		parts[i] = fmt.Sprintf("%q", s)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}
