apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: scn-grpc-gateway
  namespace: {{.Namespace}}
spec:
  gatewayClassName: {{.GatewayClassName}}
  addresses:
  - type: IPAddress
    value: {{.VIP}}
  listeners:
  - name: grpc-listener
    protocol: HTTP
    port: 50051
    allowedRoutes:
      namespaces: {from: Same}
