apiVersion: gateway.k8s.f5net.com/v1
kind: L4Route
metadata:
  name: scn-grpc-l4-route
  namespace: {{.Namespace}}
spec:
  parentRefs:
  - name: scn-grpc-l4-gateway
    sectionName: tcp-listener
  protocol: TCP
  pvaAccelerationMode: disabled
  rules:
  - backendRefs:
    - name: grpcbin-l4-svc
      port: 9000
