package config

import (
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"
)

// helper: stage a workspace dir + state-dir layout under a private
// ROKSBNKCTL_HOME for one test, return (workspace name, cleanup).
func stageWorkspace(t *testing.T) (string, string) {
	t.Helper()
	home := t.TempDir()
	t.Setenv(ROKSBNKCTLHomeEnv, home)
	ws := "appliedtest"
	wsDir, err := WorkspaceDir(ws)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(wsDir, 0o750); err != nil {
		t.Fatal(err)
	}
	// Pre-create the per-phase state dirs so WriteAppliedTFVars's
	// MkdirAll is a no-op and we can stat the output.
	stateDir, err := WorkspaceStateDir(ws)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(stateDir, 0o750); err != nil {
		t.Fatal(err)
	}
	clusterStateDir, err := WorkspaceClusterStateDir(ws)
	if err != nil {
		t.Fatal(err)
	}
	if err := os.MkdirAll(clusterStateDir, 0o750); err != nil {
		t.Fatal(err)
	}
	return ws, home
}

// TestRenderAppliedTFVars_HeaderShape pins the exact header bytes so a
// reader (or another tool) can rely on the format.
func TestRenderAppliedTFVars_HeaderShape(t *testing.T) {
	t.Parallel()
	now := time.Date(2026, 5, 18, 12, 0, 0, 0, time.UTC)
	got, err := renderAppliedTFVars("trial", nil, now, "v0.9.0-rc1")
	if err != nil {
		t.Fatal(err)
	}
	want := "# Generated by awsbnkctl v0.9.0-rc1 at 2026-05-18T12:00:00Z after terraform apply on phase=trial.\n" +
		"# Re-generated each apply. Do not edit by hand — your changes will be overwritten.\n\n"
	if got != want {
		t.Errorf("header mismatch:\ngot:\n%s\nwant:\n%s", got, want)
	}
}

// TestRenderAppliedTFVars_AssignmentsSortedAndAttributed covers the
// happy path: assignments from one source are alphabetically sorted
// under a "from <source>" section header.
func TestRenderAppliedTFVars_AssignmentsSortedAndAttributed(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	src := filepath.Join(dir, "terraform.tfvars")
	body := `# comment line — ignored
region = "us-east-1"
vpc_id = "vpc-abc123"
cluster_name = "bnk-prod"
`
	if err := os.WriteFile(src, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	now := time.Date(2026, 5, 18, 0, 0, 0, 0, time.UTC)
	got, err := renderAppliedTFVars("trial", []string{src}, now, "test")
	if err != nil {
		t.Fatal(err)
	}
	// Section header uses the basename mapped through sourceLabel.
	if !strings.Contains(got, "# === from config.yaml ===") {
		t.Errorf("missing section header in output: %s", got)
	}
	// Assignments alphabetically sorted (cluster_name < region < vpc_id).
	idxCluster := strings.Index(got, "cluster_name")
	idxRegion := strings.Index(got, "region")
	idxVPC := strings.Index(got, "vpc_id")
	if !(idxCluster > 0 && idxCluster < idxRegion && idxRegion < idxVPC) {
		t.Errorf("assignments not alphabetic: cluster_name=%d region=%d vpc_id=%d\n%s",
			idxCluster, idxRegion, idxVPC, got)
	}
}

// TestRenderAppliedTFVars_RedactsAWSStaticCreds confirms the AWS
// equivalent of upstream's ibmcloud_api_key redaction.
func TestRenderAppliedTFVars_RedactsAWSStaticCreds(t *testing.T) {
	t.Parallel()
	dir := t.TempDir()
	src := filepath.Join(dir, "terraform.tfvars")
	body := `region = "us-east-1"
aws_access_key_id = "AKIAIOSFODNN7EXAMPLE"
aws_secret_access_key = "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
aws_session_token = "FwoGZXIvYXdz..."
vpc_id = "vpc-abc"
`
	if err := os.WriteFile(src, []byte(body), 0o600); err != nil {
		t.Fatal(err)
	}

	now := time.Date(2026, 5, 18, 0, 0, 0, 0, time.UTC)
	got, err := renderAppliedTFVars("trial", []string{src}, now, "test")
	if err != nil {
		t.Fatal(err)
	}
	// None of the secret values must appear.
	for _, secret := range []string{"AKIAIOSFODNN7EXAMPLE", "wJalrXUtnFEMI", "FwoGZXIvYXdz"} {
		if strings.Contains(got, secret) {
			t.Errorf("secret material leaked into snapshot: %s\noutput:\n%s", secret, got)
		}
	}
	// All three redacted vars must appear with the redaction placeholder.
	for _, name := range []string{"aws_access_key_id", "aws_secret_access_key", "aws_session_token"} {
		want := name + ` = "<redacted>"`
		if !strings.Contains(got, want) {
			t.Errorf("expected redacted line %q in output:\n%s", want, got)
		}
	}
	// Non-redacted vars must still appear with their values.
	if !strings.Contains(got, `region = "us-east-1"`) {
		t.Errorf("expected non-redacted region in output:\n%s", got)
	}
}

// TestRenderAppliedTFVars_MissingSourceMarker covers the
// log-and-continue case for a source file that's been deleted before
// the snapshot runs.
func TestRenderAppliedTFVars_MissingSourceMarker(t *testing.T) {
	t.Parallel()
	missing := filepath.Join(t.TempDir(), "does-not-exist.tfvars")
	now := time.Date(2026, 5, 18, 0, 0, 0, 0, time.UTC)
	got, err := renderAppliedTFVars("trial", []string{missing}, now, "test")
	if err != nil {
		t.Fatalf("missing-source should be log-and-continue, got error: %v", err)
	}
	if !strings.Contains(got, "(missing)") {
		t.Errorf("expected missing-source marker in output:\n%s", got)
	}
}

// TestWriteAppliedTFVars_AtomicWriteAndMode is the integration-y test:
// writes a real snapshot, verifies path, mode, content. Hits the
// per-phase state dir routing.
func TestWriteAppliedTFVars_AtomicWriteAndMode(t *testing.T) {
	ws, _ := stageWorkspace(t)
	dir := t.TempDir()
	src := filepath.Join(dir, "terraform.tfvars")
	if err := os.WriteFile(src, []byte("region = \"us-east-1\"\n"), 0o600); err != nil {
		t.Fatal(err)
	}

	if err := WriteAppliedTFVars(ws, "trial", []string{src}); err != nil {
		t.Fatal(err)
	}
	p, err := AppliedTFVarsPath(ws, "trial")
	if err != nil {
		t.Fatal(err)
	}
	st, err := os.Stat(p)
	if err != nil {
		t.Fatalf("snapshot not written: %v", err)
	}
	// Mode must be 0600 — secrets-grade.
	if mode := st.Mode().Perm(); mode != 0o600 {
		t.Errorf("snapshot mode = %o, want 0600", mode)
	}
	body, err := os.ReadFile(p)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(string(body), `region = "us-east-1"`) {
		t.Errorf("snapshot missing expected value:\n%s", body)
	}
	// Atomic-rename leaves no temp files behind in the same dir.
	entries, err := os.ReadDir(filepath.Dir(p))
	if err != nil {
		t.Fatal(err)
	}
	for _, e := range entries {
		if strings.HasPrefix(e.Name(), ".terraform.applied.tfvars.") {
			t.Errorf("temp file left behind: %s", e.Name())
		}
	}
}

// TestAppliedTFVarsPath_PhaseRouting confirms cluster/trial/legacy-single
// land in the right per-phase state dirs.
func TestAppliedTFVarsPath_PhaseRouting(t *testing.T) {
	ws, _ := stageWorkspace(t)

	cluster, err := AppliedTFVarsPath(ws, "cluster")
	if err != nil {
		t.Fatal(err)
	}
	if !strings.Contains(cluster, "state-cluster") {
		t.Errorf("cluster phase: expected path under state-cluster/, got %s", cluster)
	}

	trial, err := AppliedTFVarsPath(ws, "trial")
	if err != nil {
		t.Fatal(err)
	}
	if strings.Contains(trial, "state-cluster") || !strings.Contains(trial, "/state/") {
		t.Errorf("trial phase: expected path under state/, got %s", trial)
	}

	legacy, err := AppliedTFVarsPath(ws, "legacy-single")
	if err != nil {
		t.Fatal(err)
	}
	if legacy != trial {
		t.Errorf("legacy-single should reuse the trial state dir; got %s vs trial %s", legacy, trial)
	}

	// Unknown phase falls through to trial — defensive fallback.
	unknown, err := AppliedTFVarsPath(ws, "wat-is-this")
	if err != nil {
		t.Fatal(err)
	}
	if unknown != trial {
		t.Errorf("unknown phase should fall through to trial dir; got %s vs trial %s", unknown, trial)
	}
}

// TestSourceLabel maps the basename → friendly-name table.
func TestSourceLabel(t *testing.T) {
	t.Parallel()
	cases := map[string]string{
		"/abs/path/terraform.tfvars":          "config.yaml",
		"terraform.tfvars":                    "config.yaml",
		"/home/u/terraform.tfvars.user":       "terraform.tfvars.user",
		"/some/other/file.tfvars":             "file.tfvars",
		"/abs/path/with spaces/custom.tfvars": "custom.tfvars",
	}
	for input, want := range cases {
		if got := sourceLabel(input); got != want {
			t.Errorf("sourceLabel(%q) = %q, want %q", input, got, want)
		}
	}
}

// TestAppliedTFVarsVersion_Fallback ensures the "dev" fallback kicks
// in when SetAppliedTFVarsVersion was never called (test binary that
// doesn't import the CLI package).
func TestAppliedTFVarsVersion_Fallback(t *testing.T) {
	// Save + restore the seam so we don't leak into other tests.
	prev := appliedTFVarsVersionFn
	appliedTFVarsVersionFn = nil
	defer func() { appliedTFVarsVersionFn = prev }()

	if got := appliedTFVarsVersion(); got != "dev" {
		t.Errorf("fallback version = %q, want \"dev\"", got)
	}

	SetAppliedTFVarsVersion(func() string { return "v9.9.9" })
	if got := appliedTFVarsVersion(); got != "v9.9.9" {
		t.Errorf("wired version = %q, want \"v9.9.9\"", got)
	}

	// Empty return falls through to "dev".
	SetAppliedTFVarsVersion(func() string { return "" })
	if got := appliedTFVarsVersion(); got != "dev" {
		t.Errorf("empty-return version = %q, want \"dev\"", got)
	}
}
