apiVersion: awsbnkctl/v1
kind: Cluster

metadata:
  name: bnk-agentcore-demo
  region: ap-southeast-2
  labels:
    purpose: bnk-agentcore-demo

pattern: host-device

network:
  vpcCidr: 10.0.0.0/16
  azs:
    - ap-southeast-2a
    - ap-southeast-2b
  subnets:
    public:
      - cidr: 10.0.1.0/24
        az: ap-southeast-2a
      - cidr: 10.0.2.0/24
        az: ap-southeast-2b
    private:
      - cidr: 10.0.11.0/24
        az: ap-southeast-2a
      - cidr: 10.0.12.0/24
        az: ap-southeast-2b
  dataPath:
    external:
      cidr: 10.0.10.0/24
      az: ap-southeast-2a
    internal:
      cidr: 10.0.20.0/24
      az: ap-southeast-2a
  natGateways: 1

cluster:
  kubernetesVersion: "1.31"
  nodeGroups:
    - name: default
      instanceType: m6i.4xlarge
      desiredSize: 3
      minSize: 3
      maxSize: 4
      diskSize: 50

addons:
  lbController:
    enabled: true

bnk:
  farArchive: /Users/j.lucia/Code/jwt-evals/cne_pull_64.json
  jwt: /Users/j.lucia/Code/jwt-evals/neysa1.jwt

testing:
  jumphost:
    enabled: true
    instanceType: c6i.4xlarge
    mgmtSubnetIndex: 0

forge:
  enabled: true
  url: http://localhost:8000
  mcpUrl: http://localhost:8081/mcp/
  credentialTemplateId: 1
  username: admin

tags:
  cost-center: RnD-AI
  env: demo
  purpose: bnk-agentcore-demo
